name: "Generate Thumbnails"
author: "Ray Villalobos"
description: "Creates thumbnails from a folder."
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "camera"
  color: "yellow"
inputs:
  email:
    description: The committer's email address
    required: true
    default: ${{ github.actor }}@localhost
  name:
    description: The committer's name
    required: true
    default: ${{ github.actor }}
