name: Generate Thumbnails
on:
  workflow_dispatch:
jobs:
  copy-to-branches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generate Thumbnails Task
        uses: planetoftheweb/generate-thumbnails
        env:
          directory: photos
          width: 500
